// Generates src/generated/version.ts with the current git commit SHA.
// Runs automatically before `dev` and `build` (see package.json predev/prebuild).
// Safe fallback to "local" when git is unavailable (e.g. fresh clone with no commit).
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";

let sha = "local";
try {
  sha = execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] })
    .toString()
    .trim();
} catch {
  // no git repo / no commits yet — keep "local"
}

const builtAt = new Date().toISOString();
const out = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.
export const COMMIT_SHA = ${JSON.stringify(sha)};
export const BUILT_AT = ${JSON.stringify(builtAt)};
`;

mkdirSync("src/generated", { recursive: true });
writeFileSync("src/generated/version.ts", out);
console.log(`[gen-version] COMMIT_SHA=${sha}`);
